Repository zipbob-lab/zipbob-dex, pull requests merged in 2024-11, with the labels that each got.

#19 Feat/main
  public/images/divide.svg
  public/images/fireEmpty.svg
  public/images/fireFilled.svg
  public/images/likeEmpty.svg
  public/images/likeFilled.svg
  public/images/scrapEmpty.svg
  src/app/(root)/page.tsx
  src/app/layout.tsx
  src/components/common/dropbox/ProfileDropbox.tsx
  src/components/layout/header/AuthStatusBar.tsx
  src/components/layout/header/Header.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/components/mainPage/RecipeCard.tsx
  src/components/mainPage/rank/LikeRanking.tsx
  src/components/mainPage/rank/Ranking.tsx
  src/components/mainPage/rank/UserCard.tsx
  src/components/mainPage/rank/UserRanking.tsx
  src/serverActions/profileAction.ts
  src/types/main.ts
Labels: feature

#21 Feat/main
  public/images/github.svg
  public/images/mainLogo.svg
  src/app/(root)/layout.tsx
  src/components/layout/AuthStatusBar.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/serverActions/profileAction.ts
Labels: fix

#29 Feat/main
  .prettierrc
  postcss.config.mjs
  src/app/(auth)/login/page.tsx
  src/app/(root)/@modal/(.)myrecipewrite/page.tsx
  src/app/(root)/mypages/page.tsx
  src/app/(root)/myrecipedetail/page.tsx
  src/app/(root)/myrecipewrite/page.tsx
  src/app/(root)/page.tsx
  src/app/(root)/scraps/page.tsx
  src/app/api/fetchSupabaseFetch.ts
  src/components/CustomToast.tsx
  src/components/RecipeCard.tsx
  src/components/UserRank.tsx
  src/components/authPage/Form/LoginForm.tsx
  src/components/authPage/Form/SignUpForm.tsx
  src/components/authPage/InputField.tsx
  src/components/authPage/SignUp/AccountSet.tsx
  src/components/authPage/SignUp/UserInfoSet.tsx
  src/components/comments/Comments.tsx
  src/components/common/ScrapModal.tsx
  src/components/common/button/LikeButton.tsx
  src/components/common/dropbox/ProfileDropbox.tsx
  src/components/fridgeList/InputAdd.tsx
  src/components/fridgeList/InputDelete.tsx
  src/components/layout/AuthStatusBar.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/components/mainPage/RecipeCard.tsx
  src/components/mainPage/rank/Ranking.tsx
  src/components/mypage/EditProfileModal.tsx
  src/components/mypage/MyPageProfile.tsx
  src/components/mypage/MyPostsCommentView.tsx
  src/components/mypage/ProfileImageUpload.tsx
  src/components/mypage/UserComment.tsx
  src/components/mypage/UserPostLists.tsx
  src/components/myrecipedetail/ModifyDeletePost.tsx
  src/components/myrecipedetail/RecipeDetailView.tsx
  src/components/myrecipewrite/ImageEditModal.tsx
  src/components/myrecipewrite/IngredientsFields.tsx
  src/components/myrecipewrite/InputField.tsx
  src/components/myrecipewrite/RecipeInfoFields.tsx
  src/types/main.ts
Labels: fix

#34 Feature/social login
  public/images/google.svg
  public/images/imageButton.svg
  public/images/kakao.svg
  public/images/loginLogo.svg
  public/images/loginPen.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(root)/layout.tsx
  src/components/authPage/Form/LoginForm.tsx
  src/components/authPage/Form/SignUpForm.tsx
  src/components/authPage/InputField.tsx
  src/components/authPage/SignUp/AccountSet.tsx
  src/components/authPage/SignUp/UserInfoSet.tsx
  src/components/common/button/GithubButton.tsx
  src/components/common/button/GoogleButton.tsx
  src/components/common/button/KakaoButton.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/styles/reset.css
  tailwind.config.ts
Labels: style

#36 Feature/social login
  public/images/deleteInput.svg
  public/images/loginPen.svg
  src/components/authPage/Form/LoginForm.tsx
  src/components/authPage/Form/SignUpForm.tsx
  src/components/authPage/InputField.tsx
  src/components/authPage/SignUp/AccountSet.tsx
  src/components/authPage/SignUp/UserInfoSet.tsx
  src/types/auth.ts
Labels: fix

#43 Feat/main
  public/images/mainSvg1.svg
  public/images/mainSvg2.svg
  public/images/rankingHat.tsx
  src/app/(root)/page.tsx
  src/app/layout.tsx
  src/components/authPage/SignUp/UserInfoSet.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/Introduce.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/components/mainPage/RecipeCard.tsx
  src/components/mainPage/rank/LikeRanking.tsx
  src/components/mainPage/rank/Ranking.tsx
  src/components/mainPage/rank/UserRanking.tsx
  tailwind.config.ts
Labels: style

#44 fix : next.config 수정
  next.config.mjs
Labels: fix

#45 style : 메인페이지와 footer 간격 수정
  src/app/(root)/page.tsx
Labels: style

#46 fix : default 유저 이미지 나오도록 수정
  src/components/mainPage/rank/UserRanking.tsx
Labels: fix

#49 Feat/main
  src/app/(root)/fridge-list/page.tsx
  src/app/(root)/page.tsx
  src/app/layout.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
Labels: style

#53 Feat/main2
  public/images/rankingHat.tsx
  src/app/(root)/fridge-list/page.tsx
  src/app/(root)/layout.tsx
  src/components/authPage/Form/LoginForm.tsx
  src/components/comments/Comments.tsx
  src/components/common/button/LikeButton.tsx
  src/components/common/dropbox/ProfileDropbox.tsx
  src/components/fridgeListPage/FridgeFilter.tsx
  src/components/layout/AuthStatusBar.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecipeCard.tsx
  src/components/mainPage/rank/LikeRanking.tsx
  src/components/myrecipedetail/ModifyDeletePost.tsx
  src/hooks/useScrap.ts
  src/hooks/useScrapData.ts
  src/store/authStore.ts
Labels: fix

#66 Feat/main2
  src/app/(root)/page.tsx
  src/components/layout/AuthStatusBar.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/Introduce.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/components/mainPage/RecipeCard.tsx
  src/components/mainPage/rank/LikeCard.tsx
  src/components/mainPage/rank/LikeRanking.tsx
  src/components/mainPage/rank/Ranking.tsx
  src/components/mainPage/rank/UserCard.tsx
  src/components/mainPage/rank/UserRanking.tsx
  tailwind.config.ts
Labels: style

#67 Feat/main2
  src/app/(auth)/login/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/authPage/Form/LoginForm.tsx
  src/components/authPage/Form/SignUpForm.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/Introduce.tsx
  src/components/mainPage/RecentRecipe.tsx
Labels: style

#73 Feat/main2
  public/images/hamburgerMenu.svg
  public/images/mobileLogo.svg
  public/images/search.svg
  src/components/authPage/Form/LoginForm.tsx
  src/components/authPage/Form/SignUpForm.tsx
  src/components/common/HamburgerMenu.tsx
  src/components/common/dropbox/ProfileDropbox.tsx
  src/components/layout/AuthStatusBar.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/Introduce.tsx
  src/serverActions/profileAction.ts
Labels: fix, style

#82 style : 스크랩버튼 프롭스 추가
  src/components/common/button/ScrapButton.tsx
  src/components/myrecipedetail/RecipeDetailView.tsx
Labels: style

#81 Feat/main2
  src/app/(auth)/login/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(root)/layout.tsx
  src/app/layout.tsx
  src/components/authPage/LoginContent.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/components/mainPage/RecipeCard.tsx
  src/components/mainPage/rank/LikeCard.tsx
  src/components/mainPage/rank/LikeRanking.tsx
  src/components/mainPage/rank/UserRanking.tsx
  src/serverActions/profileAction.ts
Labels: fix, style

#85 fix : 레시피카드2 콘솔에러 삭제, 유저닉네임 가져오는 로직 변경
  src/components/myrecipedetail/RecipeCard2.tsx
Labels: fix

#93 fix : RecentCommentCard 수정
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
Labels: fix

#94 Feat/main2
  src/app/(root)/page.tsx
  src/components/mainPage/HealthyRecipe.tsx
  src/components/mainPage/Introduce.tsx
  src/components/mainPage/RecentComment/RecentComment.tsx
  src/components/mainPage/RecentComment/RecentCommentCard.tsx
  src/components/mainPage/RecentComment/RecentCommentCardSkeleton.tsx
  src/components/mainPage/RecentRecipe.tsx
  src/components/mainPage/RecipeCardSkeleton.tsx
  src/components/mainPage/RecipeWriteButton.tsx
  src/components/mainPage/rank/LikeCard.tsx
  src/components/mainPage/rank/LikeCardSkeleton.tsx
  src/components/mainPage/rank/LikeRanking.tsx
  src/components/mainPage/rank/Ranking.tsx
  src/components/mainPage/rank/RankingPage.tsx
  src/components/mainPage/rank/UserCard.tsx
  src/components/mainPage/rank/UserCardSkeleton.tsx
  src/components/mainPage/rank/UserRanking.tsx
  src/types/main.ts
Labels: fix

#95 Feat/main2
  src/components/common/Pagination.tsx
  src/components/mainPage/Introduce.tsx
Labels: optimization
